language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t shubhamjr/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true shubhamjr/docker-react npm run test  