FROM node:18-alpine

USER node

WORKDIR /home/node/app

RUN mkdir -p /home/node/app

COPY --chown=node:node ./package.json ./

RUN npm install -g npm@8.11.0

# RUN chown node:node /home/node/app
RUN sudo chown -R $USER /home/node/app

RUN npm install --fetch-timeout=600000

COPY --chown=node:node . .

CMD ["npm","start"]